import type { Metadata } from 'next'
import { Providers } from './providers'
import { ColorModeScript } from '@chakra-ui/react'
import { cookies } from 'next/headers'
import theme from './theme'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const token = cookies().get('refreshToken')?.value
  return (
    <html lang='en' suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <Providers initialToken={token}>{children}</Providers>
      </body>
    </html>
  )
}
